name       : python-jupyterlab-pygments
version    : 0.1.2
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/j/jupyterlab_pygments/jupyterlab_pygments-0.1.2.tar.gz : cfcda0873626150932f438eccf0f8bf22bfa92345b814890ab360d666b254146
homepage   : https://jupyter.org/
license    : BSD-3-Clause
component  : programming.python
summary    : Pygments theme using JupyterLab CSS variables
description: |
    Pygments theme using JupyterLab CSS variables.
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-wheel
rundeps    :
    - pygments
build      : |
    %python3_setup
install    : |
    %python3_install
