name       : python-jupyterlab-pygments
version    : 0.2.2
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/j/jupyterlab_pygments/jupyterlab_pygments-0.2.2.tar.gz : 7405d7fde60819d905a9fa8ce89e4cd830e318cdad22a0030f7a901da705585d
homepage   : https://github.com/jupyterlab/jupyterlab_pygments
license    : BSD-3-Clause
component  : programming.python
summary    : Pygments theme using JupyterLab CSS variables
description: |
    This package contains a syntax coloring theme for pygments making use of the JupyterLab CSS variables. The goal is to enable the use of JupyterLab's themes with pygments-generated HTML.
builddeps  :
    - python-build
    - python-installer
    - python-jupyter-packaging
    - python-packaging
    - python-wheel
rundeps    :
    - pygments
build      : |
    %python3_setup
install    : |
    %python3_install
